apiVersion: v1
kind: ConfigMap
metadata:
  name: sync-config
  namespace: postgres-starrocks-sync
data:
  # Application Configuration
  CONFIG_PATH: "/app/config/production_config.yaml"
  LOG_LEVEL: "INFO"
  LOG_JSON_FORMAT: "true"
  LOG_STRUCTURED: "true"
  
  # Database Configuration
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "production_db"
  POSTGRES_USER: "postgres"
  
  STARROCKS_HOST: "starrocks-fe-service"
  STARROCKS_PORT: "8030"
  STARROCKS_DB: "production_db"
  STARROCKS_USER: "root"
  
  # Flink Configuration
  FLINK_JOBMANAGER_HOST: "flink-jobmanager-service"
  FLINK_JOBMANAGER_PORT: "8081"
  FLINK_PARALLELISM: "8"
  
  # Monitoring Configuration
  METRICS_PORT: "9090"
  HEALTH_CHECK_PORT: "8080"
  
  # Environment
  ENVIRONMENT: "production"
  
  # Sync Tables Configuration
  SYNC_TABLES: |
    users,users,id,id|username|email|first_name|last_name|created_at|updated_at|is_active,cdc,2000,30,true;
    orders,orders,id,id|user_id|product_id|quantity|price|status|created_at|updated_at|shipped_at,cdc,2000,30,true;
    products,products,id,id|name|description|price|category_id|in_stock|created_at|updated_at,cdc,2000,30,true;
    categories,categories,id,id|name|description|parent_id|created_at|updated_at,cdc,1000,60,true

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: postgres-starrocks-sync
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    rule_files:
      - "alert_rules.yml"
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - alertmanager:9093
    
    scrape_configs:
      - job_name: 'sync-app'
        static_configs:
          - targets: ['sync-app-service:9090']
        scrape_interval: 10s
        metrics_path: /metrics
      
      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter:9187']
        scrape_interval: 30s
      
      - job_name: 'starrocks'
        static_configs:
          - targets: ['starrocks-exporter:8080']
        scrape_interval: 30s
      
      - job_name: 'flink'
        static_configs:
          - targets: ['flink-jobmanager-service:8081']
        scrape_interval: 30s
        metrics_path: /metrics

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: postgres-starrocks-sync
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
        editable: true
