version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: demo_postgres
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - demo_network

  # Using MySQL as StarRocks alternative for demo
  starrocks:
    image: mysql:8.0
    container_name: demo_starrocks_fe
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
      MYSQL_USER: demo_user
      MYSQL_PASSWORD: demo_password
    ports:
      - "3307:3306"  # MySQL port
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - demo_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  flink-jobmanager:
    image: flink:1.16-scala_2.12
    container_name: demo_flink_jobmanager
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 1
        jobmanager.memory.process.size: 1600m
        taskmanager.memory.process.size: 1728m
    ports:
      - "8081:8081"
    networks:
      - demo_network

  flink-taskmanager:
    image: flink:1.16-scala_2.12
    container_name: demo_flink_taskmanager
    command: taskmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: flink-jobmanager
        taskmanager.numberOfTaskSlots: 2
        parallelism.default: 1
        jobmanager.memory.process.size: 1600m
        taskmanager.memory.process.size: 1728m
    depends_on:
      - flink-jobmanager
    networks:
      - demo_network

  sync-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo_sync_app
    ports:
      - "8080:8080"  # Health check port
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=demo_db
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
      - STARROCKS_HOST=starrocks
      - STARROCKS_PORT=3307
      - STARROCKS_USER=root
      - STARROCKS_PASSWORD=root
    depends_on:
      - postgres
      - starrocks
      - flink-jobmanager
    networks:
      - demo_network
    volumes:
      - ./src:/app/src
      - ./config:/app/config

volumes:
  postgres_data:
  starrocks_data:

networks:
  demo_network:
    driver: bridge
