global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Sync Application
  - job_name: 'sync-app'
    static_configs:
      - targets: ['sync-app:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # StarRocks Exporter (if available)
  - job_name: 'starrocks'
    static_configs:
      - targets: ['starrocks-exporter:8080']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Flink JobManager
  - job_name: 'flink'
    static_configs:
      - targets: ['flink-jobmanager:8081']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Node Exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s
